language: php

php:
  - 7.2

before_install:
  - composer self-update
  - composer config repositories.packagist.com composer https://repo.packagist.com/snowio/
  - if [[ -n $PACKAGIST_TOKEN ]]; then composer config http-basic.repo.packagist.com token $PACKAGIST_TOKEN; fi
  - if [[ -n $GITHUB_TOKEN ]]; then composer config github-oauth.github.com $GITHUB_TOKEN; fi

install:
  - composer install

script:
  - php vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
